### ISSUE TITLE
Desarrollo del algoritmo para colocación de piezas

### ISSUE THREAD

**Issue by 0xEileen** [ariano-m/AIVA_2024_MADERAS#10]
Se planteará y codificará un algoritmo encargado de encontrar la posición óptima de las piezas sobre las tablas de madera para que estas no se sitúen sobre ninguna imperfección y aprovechen la materia prima al máximo.
El tiempo estimado es de 3 días.

**Comment by ariano-m** [comment]
Tiempo empleado: 2 días
